# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

repos:
- repo: https://github.com/golangci/golangci-lint
  rev: v2.1.5
  hooks:
    - id: golangci-lint
    - id: golangci-lint-fmt
