name: Terraform Provider Acceptance Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: make generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate' command and commit."; exit 1)

  test:
    name: Terraform Provider Acceptance Tests
    needs: [ build, generate ]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
    env:
      METABASE_API_KEY: "" # Will be set dynamically
      METABASE_HOST: "localhost:3000"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - name: Start Metabase and PostgreSQL with Docker Compose
        run: docker compose -f tools/docker-compose.yml up -d
      - name: Wait for Metabase to be ready
        run: |
          echo "Waiting for Metabase to be ready..."
          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/health | grep "200"; do
            echo "Metabase not ready yet. Waiting 5 seconds..."
            sleep 5
          done
          echo "Metabase is ready!"

      - name: Run Metabase API Key setup script
        run: |
          chmod +x ./tools/init-metabase.sh
          API_KEY=$(./tools/init-metabase.sh)
          echo "METABASE_API_KEY=$API_KEY" >> $GITHUB_ENV
      - name: Display API Key
        run: |
          echo "Metabase API Key: ${{ env.METABASE_API_KEY }}"
      - run: go mod download
      - name: Run acceptance tests
        env:
          TF_ACC: "1"
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 20
      - name: Stop Metabase and PostgreSQL
        if: always()
        run: docker compose -f tools/docker-compose.yml down --volumes
